#pragma once

#include <Layout/LSWMenuLayout.h>
#include <Layout/LSWWidgetLayout.h>
#include <Widget/LSWWidget.h>

using namespace lsw;

namespace mx {

	class CDeusHexMachinaLayout {
	public :
		// == Enumerations.
		// Control ID's.
		enum MX_WINDOW_IDS {
			MX_W_NONE,
			MX_W_MAINWINDOW						= 3950,
			MX_W_STATUSBAR,
			MX_W_TOOLBAR0,
			MX_W_REBAR0,
			MX_W_TABS,

			MX_W_TAB_START,
		};

		// Menu items.
		enum MX_MENU_IDS {
			MX_M_MENU_BAR						= 1080,
			MX_M_MENU_FILE,
			MX_M_MENU_EDIT,
			MX_M_MENU_SELECT,
			MX_M_MENU_FIND,
			MX_M_MENU_VIEW,
			MX_M_MENU_FORMAT,
			MX_M_MENU_SCRIPTS,
			MX_M_MENU_TEMPLATES,
			MX_M_MENU_TOOLS,
			MX_M_MENU_WINDOW,
			MX_M_MENU_HELP,

			MX_M_FILE							= 1100,
			MX_M_FILE_OPENFILE,
			MX_M_FILE_OPENCURPROCESS,
			MX_M_FILE_OPENPROCESS,
			MX_M_FILE_OPENRECENT,
			MX_M_FILE_SAVE,
			MX_M_FILE_SAVE_AS,
			MX_M_FILE_SAVE_A_COPY,
			MX_M_FILE_SAVE_SELECTION,
			MX_M_FILE_SAVE_ALL,
			MX_M_FILE_CLOSE,
			MX_M_FILE_CLOSE_ALL,
			MX_M_FILE_REVERT_REFRESH,
			MX_M_FILE_RENAME_FILE,
			MX_M_FILE_DELETE_FILE,
			MX_M_FILE_IMPORT_HEX,
			MX_M_FILE_EXPORT_HEX,
			MX_M_FILE_EXIT,

			MX_M_EDIT,
			MX_M_EDIT_UNDO,
			MX_M_EDIT_REDO,
			MX_M_EDIT_CUT,
			MX_M_EDIT_COPY,
			MX_M_EDIT_COPY_AS_HEX,
			MX_M_EDIT_PASTE,
			MX_M_EDIT_PASTE_SPECIAL,
			MX_M_EDIT_PASTE_FROM_HEX_TEXT,
			MX_M_EDIT_DELETE,
			MX_M_EDIT_SELECT_ALL,
			MX_M_EDIT_SELECT_RANGE,
			MX_M_EDIT_INSERT_FILE,
			MX_M_EDIT_INSERT_BYTES,
			MX_M_EDIT_OVERWRITE_FILE,
			MX_M_EDIT_OVERWRITE_BYTES,
			MX_M_EDIT_INSERT_DATE,
			MX_M_EDIT_SET_FILE_SIZE,
			MX_M_EDIT_READ_ONLY,
			MX_M_EDIT_KEEP_FILE_TIME,
			MX_M_EDIT_PROPERTIES,

			MX_M_SELECT,
			// MX_M_EDIT_SELECT_ALL,
			MX_M_SELECT_WORD,
			MX_M_SELECT_LINE,
			//MX_M_EDIT_SELECT_RANGE,
			MX_M_SELECT_EXPAND_SELECTION,
			MX_M_SELECT_REVSERSE_SELECTION,
			MX_M_SELECT_MARK_SELECTION_START,
			MX_M_SELECT_MARK_SELECTION_END,
			MX_M_SELECT_COLUMN_MODE,
			MX_M_SELECT_MOVE_SELECTION_BACK,
			MX_M_SELECT_MOVE_SELECTION_FORWARD,
			
			MX_M_FIND,
			MX_M_FIND_FIND,
			MX_M_FIND_FIND_NEXT,
			MX_M_FIND_FIND_PREV,
			MX_M_FIND_REPLACE,
			MX_M_FIND_REPLACE_NEXT,
			MX_M_FIND_REPLACE_PREV,
			MX_M_FIND_FIND_STRINGS,
			MX_M_FIND_FIND_IN_FILES,
			MX_M_FIND_REPLACE_IN_FILES,
			MX_M_FIND_GOTO,
			MX_M_FIND_GOTO_AGAIN,
			MX_M_FIND_ADD_BOOKMARK,
			MX_M_FIND_TOGGLE_BOOKMARK,
			MX_M_FIND_NEXT_BOOKMARK,
			MX_M_FIND_PREV_BOOKMARK,
			MX_M_FIND_CLEAR_BOOKMARKS,
			MX_M_FIND_JUMP_TO_TEMPLATE_VARIABLE,

			MX_M_VIEW,
			MX_M_VIEW_EDIT_AS_TEXT,
			MX_M_VIEW_EDIT_AS_HEX,
			MX_M_VIEW_EDIT_AS_BINARY,
			MX_M_VIEW_EDIT_AS_SCRIPT,
			MX_M_VIEW_EDIT_AS_TEMPLATE,
			MX_M_VIEW_EDIT_AS_EBCDIC,
			MX_M_VIEW_EDIT_AS_UNICODE,
			MX_M_VIEW_EDIT_AS_UTF_8,
			MX_M_VIEW_EDIT_AS_PROCESS,
			MX_M_VIEW_EDIT_AS_CODE,
			MX_M_VIEW_FONT,
			MX_M_VIEW_CHARACTER_SET,
			MX_M_VIEW_LINE_NUMBERS_ADDRESSES,
			MX_M_VIEW_TABS_WHITESPACE,
			MX_M_VIEW_SYNTAX,
			MX_M_VIEW_LINEFEEDS,
			MX_M_VIEW_LINE_WIDTH,
			MX_M_VIEW_GROUP_BY,
			MX_M_VIEW_DIVISION_LINES,
			MX_M_VIEW_LEFT_AREAS,
			MX_M_VIEW_RIGHT_AREA,
			MX_M_VIEW_HIGHLIGHTING,
			MX_M_VIEW_RULER,
			MX_M_VIEW_MINI_MAP,
			MX_M_VIEW_STATUS_BAR_FILE_POS_FORMAT,
			MX_M_VIEW_STATUS_BAR_FILE_SIZE_FORMAT,
			MX_M_VIEW_STATUS_BAR_SEL_SIZE_FORMAT,
			MX_M_VIEW_STATUS_BAR_BYTE_VALUE_FORMAT,
			MX_M_VIEW_ENDIAN,

			MX_M_FORMAT,
			MX_M_FORMAT_UPPERCASE,
			MX_M_FORMAT_LOWERCASE,
			MX_M_FORMAT_CAPITALIZE,
			MX_M_FORMAT_DUPLICATE,
			MX_M_FORMAT_MOVE_LINES_UP,
			MX_M_FORMAT_MOVE_LINES_DOWN,
			MX_M_FORMAT_TABIFY,
			MX_M_FORMAT_UNTABIFY,
			MX_M_FORMAT_COMMENT_SELECTION,
			MX_M_FORMAT_UNCOMMENT_SELECTION,
			MX_M_FORMAT_INCREASE_LINE_INDENT,
			MX_M_FORMAT_DECREASE_LINE_INDENT,
			MX_M_FORMAT_DELETE_LINE,
			MX_M_FORMAT_DELETE_BLANK_LINES,
			MX_M_FORMAT_DELETE_LEFT_WORD,
			MX_M_FORMAT_DELETE_RIGHT_WORD,
			MX_M_FORMAT_DELETE_TO_END_OF_LINE,
			MX_M_FORMAT_TRIM_TRAILING_WHITESPACE,
			
			MX_M_SCRIPTS,
			MX_M_SCRIPTS_NEW,
			MX_M_SCRIPTS_OPEN,
			MX_M_SCRIPTS_EDIT,
			MX_M_SCRIPTS_RUN,
			MX_M_SCRIPTS_CONTINUE,
			MX_M_SCRIPTS_STOP,
			MX_M_SCRIPTS_INSTALLED_LIST,

			MX_M_TEMPLATES,
			MX_M_TEMPLATES_NEW,
			MX_M_TEMPLATES_OPEN,
			MX_M_TEMPLATES_EDIT,
			MX_M_TEMPLATES_RUN,
			MX_M_TEMPLATES_CONTINUE,
			MX_M_TEMPLATES_STOP,
			MX_M_TEMPLATES_INSTALLED_LIST,

			MX_M_TOOLS,
			MX_M_TOOLS_EXPRESSION_EVALUATOR,
			MX_M_TOOLS_COMPARE_FILES,
			MX_M_TOOLS_HEX_OPERATIONS,
			MX_M_TOOLS_CONVERT,
			MX_M_TOOLS_HISTOGRAM,
			MX_M_TOOLS_CHECK_SUM,
			MX_M_TOOLS_DISASSEMBLER,
			MX_M_TOOLS_BASE_CONVERTER,
			MX_M_TOOLS_OPTIONS,
		};


		// == Functions.
		// Creates the PE Works window.
		static CWidget *						CreateDeusHexMachinaWindow( CWidget * _pwParent );


	protected :
		// == Members.
		// The layout for the PE Works window.
		static LSW_WIDGET_LAYOUT				m_wlMainWindow[];

		// Menu bar items for the main window.
		static LSW_MENU_ITEM					m_miMenuBar[];

		// File menu.
		static LSW_MENU_ITEM					m_miFileMenu[];

		// Menus.
		static LSW_MENU_LAYOUT					m_miMenus[];
	};

}	// namespace mx
