#pragma once

#include "../Strings/MXStringDecoder.h"

#ifndef MX_MAIN_WINDOW_W
#define MX_MAIN_WINDOW_W				772
#endif	// MX_MAIN_WINDOW_W

#ifndef MX_MAIN_WINDOW_H
#define MX_MAIN_WINDOW_H				605
#endif	// MX_MAIN_WINDOW_H

#ifndef MX_LOCK_LEFT
#define MX_LOCK_LEFT					_T_BA1A357D_____SL______P__L_____P__SL_, _LEN_BA1A357D
#endif	// MX_LOCK_LEFT

#ifndef MX_LOCK_RIGHT
#define MX_LOCK_RIGHT					_T_E9370281_____SR______P__R_____P__SR_, _LEN_E9370281
#endif	// MX_LOCK_RIGHT

#ifndef MX_LOCK_TOP
#define MX_LOCK_TOP						_T_22A15A67_____ST______P__T_____P__ST_, _LEN_22A15A67
#endif	// MX_LOCK_TOP

#ifndef MX_LOCK_BOTTOM
#define MX_LOCK_BOTTOM					_T_061AB76D_____SB______P__B_____P__SB_, _LEN_061AB76D
#endif	// MX_LOCK_BOTTOM

#ifndef MX_FIXED_WIDTH
#define MX_FIXED_WIDTH					_T_B4414AD5_____W, _LEN_B4414AD5
#endif	// MX_FIXED_WIDTH

#ifndef MX_FIXED_HEIGHT
#define MX_FIXED_HEIGHT					_T_39494720_____H, _LEN_39494720
#endif	// MX_FIXED_WIDTH

#ifndef MX_PARENT_CLEFT
#define MX_PARENT_CLEFT					_T_C8D9229E_____P__CL, _LEN_C8D9229E
#endif	// MX_PARENT_CLEFT

#ifndef MX_PARENT_CRIGHT
#define MX_PARENT_CRIGHT				_T_32D61FFD_____P__CR, _LEN_32D61FFD
#endif	// MX_PARENT_CRIGHT

#ifndef MX_PARENT_CTOP
#define MX_PARENT_CTOP					_T_DBB5BAC8_____P__CT, _LEN_DBB5BAC8
#endif	// MX_PARENT_CTOP

#ifndef MX_PARENT_CBOTTOM
#define MX_PARENT_CBOTTOM				_T_2F610F99_____P__CB, _LEN_2F610F99
#endif	// MX_PARENT_CBOTTOM

#ifndef MX_PARENT_CWIDTH
#define MX_PARENT_CWIDTH				_T_42BCEB72_____P__CW, _LEN_42BCEB72
#endif	// MX_PARENT_CWIDTH

#ifndef MX_PARENT_CHEIGHT
#define MX_PARENT_CHEIGHT				_T_CFB4E687_____P__CH, _LEN_CFB4E687
#endif	// MX_PARENT_CHEIGHT

#ifndef MX_PARENT_VCLEFT
#define MX_PARENT_VCLEFT				_T_2762F803_____P__VCL, _LEN_2762F803
#endif	// MX_PARENT_VCLEFT

#ifndef MX_PARENT_VCRIGHT
#define MX_PARENT_VCRIGHT				_T_DD6DC560_____P__VCR, _LEN_DD6DC560
#endif	// MX_PARENT_VCRIGHT

#ifndef MX_PARENT_VCTOP
#define MX_PARENT_VCTOP					_T_340E6055_____P__VCT, _LEN_340E6055
#endif	// MX_PARENT_VCTOP

#ifndef MX_PARENT_VCBOTTOM
#define MX_PARENT_VCBOTTOM				_T_C0DAD504_____P__VCB, _LEN_C0DAD504
#endif	// MX_PARENT_VCBOTTOM

#ifndef MX_PARENT_VCWIDTH
#define MX_PARENT_VCWIDTH				_T_AD0731EF_____P__VCW, _LEN_AD0731EF
#endif	// MX_PARENT_VCWIDTH

#ifndef MX_PARENT_VCHEIGHT
#define MX_PARENT_VCHEIGHT				_T_200F3C1A_____P__VCH, _LEN_200F3C1A
#endif	// MX_PARENT_VCHEIGHT

#ifndef MX_TOP_VCOFFSET
#define MX_TOP_VCOFFSET					_T_3F4DAEFB_____P__VCT_____SCT, _LEN_3F4DAEFB
#endif	// MX_TOP_VCOFFSET

#ifndef MX_CHECKSTYLE
#define MX_CHECKSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX
#endif	// MX_CHECKSTYLE

#ifndef MX_RADIOSTYLE
#define MX_RADIOSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_AUTORADIOBUTTON
#endif	// MX_RADIOSTYLE

#ifndef MX_STATICSTYLE
#define MX_STATICSTYLE					WS_CHILDWINDOW | WS_VISIBLE | SS_LEFT
#endif	// MX_STATICSTYLE

#ifndef MX_BUTTONSTYLE
#define MX_BUTTONSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON | BS_TEXT
#endif	// MX_BUTTONSTYLE

#ifndef MX_DEFBUTTONSTYLE
#define MX_DEFBUTTONSTYLE				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON | BS_TEXT
#endif	// MX_DEFBUTTONSTYLE

#ifndef MX_GROUPSTYLE
#define MX_GROUPSTYLE					WS_CHILDWINDOW | WS_VISIBLE | BS_GROUPBOX
#endif	// MX_GROUPSTYLE

#ifndef MX_EDITSTYLE
#define MX_EDITSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | ES_LEFT | ES_AUTOHSCROLL
#endif	// MX_EDITSTYLE

#ifndef MX_COMBOSTYLE
#define MX_COMBOSTYLE					WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | CBS_DROPDOWN | CBS_HASSTRINGS | CBS_AUTOHSCROLL
#endif	// MX_COMBOSTYLE

#ifndef MX_COMBOSTYLE_LIST
#define MX_COMBOSTYLE_LIST				WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | CBS_DROPDOWNLIST | CBS_HASSTRINGS/* | CBS_AUTOHSCROLL*/ | WS_VSCROLL
#endif	// MX_COMBOSTYLE_LIST

#ifndef MX_COMBOSTYLEEX_LIST
#define MX_COMBOSTYLEEX_LIST			0//WS_EX_NOPARENTNOTIFY
#endif	// MX_COMBOSTYLEEX_LIST

#ifndef MX_DEF_STATIC_HEIGHT
#define MX_DEF_STATIC_HEIGHT			8	// Dialog units.
#endif	// MX_DEF_STATIC_HEIGHT

#ifndef MX_DEF_STATIC_HEIGHT_PXL
#define MX_DEF_STATIC_HEIGHT_PXL		15	// Pixels
#endif	// MX_DEF_STATIC_HEIGHT_PXL

#ifndef MX_DEF_CHECK_HEIGHT
#define MX_DEF_CHECK_HEIGHT				9	// Dialog units.
#endif	// MX_DEF_CHECK_HEIGHT

#ifndef MX_DEF_CHECK_HEIGHT_PXL
#define MX_DEF_CHECK_HEIGHT_PXL			17	// Pixels.
#endif	// MX_DEF_CHECK_HEIGHT_PXL

#ifndef MX_DEF_RADIO_HEIGHT
#define MX_DEF_RADIO_HEIGHT				9	// Dialog units.
#endif	// MX_DEF_RADIO_HEIGHT

#ifndef MX_DEF_RADIO_HEIGHT_PXL
#define MX_DEF_RADIO_HEIGHT_PXL			17	// Pixels.
#endif	// MX_DEF_RADIO_HEIGHT_PXL

#ifndef MX_DEF_EDIT_HEIGHT
#define MX_DEF_EDIT_HEIGHT				12	// Dialog units.
#endif	// MX_DEF_EDIT_HEIGHT

#ifndef MX_DEF_EDIT_HEIGHT_PXL
#define MX_DEF_EDIT_HEIGHT_PXL			23	// Pixels.
#endif	// MX_DEF_EDIT_HEIGHT_PXL

#ifndef MX_DEF_COMBO_HEIGHT
#define MX_DEF_COMBO_HEIGHT				12	// Dialog units.
#endif	// MX_DEF_COMBO_HEIGHT

#ifndef MX_DEF_COMBO_HEIGHT_PXL
#define MX_DEF_COMBO_HEIGHT_PXL			23	// Pixels.
#endif	// MX_DEF_COMBO_HEIGHT_PXL

#ifndef MX_DEF_BUTTON_HEIGHT
#define MX_DEF_BUTTON_HEIGHT			12	// Dialog units.
#endif	// MX_DEF_BUTTON_HEIGHT

#ifndef MX_DEF_BUTTON_HEIGHT_PXL
#define MX_DEF_BUTTON_HEIGHT_PXL		23	// Pixels.
#endif	// MX_DEF_BUTTON_HEIGHT_PXL

#ifndef MX_DEF_BUTTON_WIDTH
#define MX_DEF_BUTTON_WIDTH				43	// Dialog units.
#endif	// MX_DEF_BUTTON_WIDTH

#ifndef MX_DEF_BUTTON_WIDTH_PXL
#define MX_DEF_BUTTON_WIDTH_PXL			75	// Pixels.
#endif	// MX_DEF_BUTTON_WIDTH_PXL

#ifndef MX_GROUP_LEFT
#define MX_GROUP_LEFT					5	// Dialog units.
#endif	// MX_GROUP_LEFT

#ifndef MX_GROUP_LEFT_PXL
#define MX_GROUP_LEFT_PXL				9	// Pixels.
#endif	// MX_GROUP_LEFT_PXL

#ifndef MX_GROUP_RIGHT
#define MX_GROUP_RIGHT					MX_GROUP_LEFT		// Dialog units.
#endif	// MX_GROUP_RIGHT

#ifndef MX_GROUP_RIGHT_PXL
#define MX_GROUP_RIGHT_PXL				MX_GROUP_LEFT_PXL	// Pixels.
#endif	// MX_GROUP_RIGHT_PXL

#ifndef MX_GROUP_TOP
#define MX_GROUP_TOP					9	// Dialog units.
#endif	// MX_GROUP_TOP

#ifndef MX_GROUP_TOP_PXL
#define MX_GROUP_TOP_PXL				17	// Pixels.
#endif	// MX_GROUP_TOP_PXL

#ifndef MX_GROUP_BOTTOM
#define MX_GROUP_BOTTOM					4	// Dialog units.
#endif	// MX_GROUP_BOTTOM

#ifndef MX_LEFT_JUST
#define MX_LEFT_JUST					2	// Dialog units.
#endif	// MX_LEFT_JUST

#ifndef MX_TOP_JUST
#define MX_TOP_JUST						2	// Dialog units.
#endif	// MX_TOP_JUST