#pragma once

#include "../Strings/MXStringDecoder.h"

#ifndef MX_LOCK_LEFT
#define MX_LOCK_LEFT		_T_BA1A357D_____SL______P__L_____P__SL_, _LEN_BA1A357D
#endif	// MX_LOCK_LEFT

#ifndef MX_LOCK_RIGHT
#define MX_LOCK_RIGHT		_T_E9370281_____SR______P__R_____P__SR_, _LEN_E9370281
#endif	// MX_LOCK_RIGHT

#ifndef MX_LOCK_TOP
#define MX_LOCK_TOP		_T_22A15A67_____ST______P__T_____P__ST_, _LEN_22A15A67
#endif	// MX_LOCK_TOP

#ifndef MX_LOCK_BOTTOM
#define MX_LOCK_BOTTOM		_T_061AB76D_____SB______P__B_____P__SB_, _LEN_061AB76D
#endif	// MX_LOCK_BOTTOM

#ifndef MX_FIXED_WIDTH
#define MX_FIXED_WIDTH		_T_B4414AD5_____W, _LEN_B4414AD5
#endif	// MX_FIXED_WIDTH

#ifndef MX_FIXED_HEIGHT
#define MX_FIXED_HEIGHT		_T_39494720_____H, _LEN_39494720
#endif	// MX_FIXED_WIDTH

#ifndef MX_CHECKSTYLE
#define MX_CHECKSTYLE			WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX
#endif	// MX_CHECKSTYLE

#ifndef MX_RADIOSTYLE
#define MX_RADIOSTYLE			WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_RADIOBUTTON
#endif	// MX_RADIOSTYLE

#ifndef MX_STATICSTYLE
#define MX_STATICSTYLE			WS_CHILDWINDOW | WS_VISIBLE | WS_GROUP | SS_LEFT
#endif	// MX_STATICSTYLE

#ifndef MX_BUTTONSTYLE
#define MX_BUTTONSTYLE			WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON | BS_TEXT
#endif	// MX_BUTTONSTYLE

#ifndef MX_DEFBUTTONSTYLE
#define MX_DEFBUTTONSTYLE		WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON | BS_TEXT
#endif	// MX_DEFBUTTONSTYLE

#ifndef MX_GROUPSTYLE
#define MX_GROUPSTYLE			WS_CHILDWINDOW | WS_VISIBLE | BS_GROUPBOX
#endif	// MX_GROUPSTYLE

#ifndef MX_EDITSTYLE
#define MX_EDITSTYLE			WS_CHILDWINDOW | WS_VISIBLE | WS_TABSTOP | WS_GROUP | ES_LEFT | ES_AUTOHSCROLL
#endif	// MX_EDITSTYLE

#ifndef MX_DEF_STATIC_HEIGHT
#define MX_DEF_STATIC_HEIGHT	8
#endif	// MX_DEF_STATIC_HEIGHT

#ifndef MX_DEF_CHECK_HEIGHT
#define MX_DEF_CHECK_HEIGHT		9
#endif	// MX_DEF_CHECK_HEIGHT

#ifndef MX_DEF_RADIO_HEIGHT
#define MX_DEF_RADIO_HEIGHT		9
#endif	// MX_DEF_RADIO_HEIGHT

#ifndef MX_DEF_EDIT_HEIGHT
#define MX_DEF_EDIT_HEIGHT		12
#endif	// MX_DEF_EDIT_HEIGHT