#pragma once
#include "../MXMhsX.h"
#include "../MemHack/MXMemHack.h"
#include "../Options/MXOptions.h"
#include <Layout/LSWWidgetLayout.h>
#include <Widget/LSWWidget.h>

using namespace lsw;

namespace mx {

	class CNewStringSearchLayout {
	public :
		// == Enumerations.
		// Control ID's.
		enum MX_STRING_SEARCH_IDS {
			MX_SSI_NONE,
			MX_SSI_DIALOG					= 4100,
			
			MX_SSI_SEARCH_GROUP,
			MX_SSI_TYPE_LABEL,
			MX_SSI_CHAR_TYPE_LABEL,
			MX_SSI_REGEX_ENCODING_LABEL,
			MX_SSI_STRING_TYPE_COMBO,
			MX_SSI_CHAR_TYPE_COMBO,
			MX_SSI_REGEX_ENCODING_COMBO,
			MX_SSI_STRING_TO_FIND_LABEL,
			MX_SSI_STRING_TO_FIND_COMBO,
			MX_SSI_PREVIEW_LABEL,
			MX_SSI_PREVIEW_EDIT,
			MX_SSI_PREVIEW_HEX_EDIT,
			MX_SSI_OPTIONS_GROUP,
			MX_SSI_REGEX_FLAVOR_LABEL,
			MX_SSI_REGEX_FLAVOR_COMBO,
			MX_SSI_UTF_HELPER_LABEL,
			MX_SSI_UTF_HELPER_COMBO,
			MX_SSI_REGEX_HELPER_LABEL,
			MX_SSI_REGEX_HELPER_COMBO,
			MX_SSI_BYTE_HELPER_LABEL,

			MX_SSI_IGNORE_CASE_CHECK,
			MX_SSI_ALIGNED_CHECK,
			MX_SSI_WHOLE_WORD_CHECK,
			MX_SSI_HEX_CHECK,
			MX_SSI_ESCAPES_CHECK,
			MX_SSI_WILDCARD_CHECK,

			MX_SSI_LINGUISTIC_IGNORECASE_CHECK,
			MX_SSI_LINGUISTIC_IGNOREDIACRITIC_CHECK,
			MX_SSI_NORM_IGNOREKANATYPE_CHECK,
			MX_SSI_NORM_IGNORENONSPACE_CHECK,
			MX_SSI_NORM_IGNORESYMBOLS_CHECK,
			MX_SSI_NORM_IGNOREWIDTH_CHECK,

			MX_SSI_REGEX_SINGLELINE,
			MX_SSI_REGEX_MULTILINE,
			MX_SSI_REGEX_EXTENDED,
			MX_SSI_REGEX_FIND_LONGEST,
			//MX_SSI_REGEX_IGNORE_EMPTY,
			MX_SSI_REGEX_NEGATE_SINGLELINE,
			MX_SSI_GENERAL_SEARCH_OPTIONS_BUTTON,
			
			MX_SSI_SEARCH_RANGE_GROUP,
			MX_SSI_FROM_LABEL,
			MX_SSI_TO_LABEL,
			MX_SSI_FROM_COMBO,
			MX_SSI_TO_COMBO,
			MX_SSI_SEARCH_BUTTON,

			MX_SSI_TOOLTIP_MATCH_CASE_CHECK,
			MX_SSI_TOOLTIP_ALIGNED_CHECK,
			MX_SSI_TOOLTIP_WHOLE_WORD_CHECK,
			MX_SSI_TOOLTIP_HEX_CHECK,
			MX_SSI_TOOLTIP_ESCAPES_CHECK,
			MX_SSI_TOOLTIP_WILDCARD_CHECK,

			MX_SSI_TOOLTIP_LINGUISTIC_IGNORECASE_CHECK,
			MX_SSI_TOOLTIP_LINGUISTIC_IGNOREDIACRITIC_CHECK,
			MX_SSI_TOOLTIP_NORM_IGNOREKANATYPE_CHECK,
			MX_SSI_TOOLTIP_NORM_IGNORENONSPACE_CHECK,
			MX_SSI_TOOLTIP_NORM_IGNORESYMBOLS_CHECK,
			MX_SSI_TOOLTIP_NORM_IGNOREWIDTH_CHECK,
			MX_SSI_TOOLTIP_GENERAL_SEARCH_OPTIONS_BUTTON,

			MX_SSI_CANCEL,
			MX_SSI_OK,
		};


		// == Functions.
		// Creates the New String Search dialog.  Makes an in-memory copy of the LSW_WIDGET_LAYOUT's so it can decode strings etc.
		static DWORD							CreateNewStringSearchDialog( CWidget * _pwParent, CMemHack * _pmhMemHack );


	protected :
		// == Members.
		// The layout for the New String Search dialog.
		static LSW_WIDGET_LAYOUT				m_wlNewStringSearchDialog[];
	};

}	// namespace mx
